export const CREATE_AUDITOR = 'CREATE_AUDITOR';
export const CREATE_AUDITOR_SUCCESS = 'CREATE_AUDITOR_SUCCESS';
export const CREATE_AUDITOR_FAIL = 'CREATE_AUDITOR_FAIL';

export const VOTE = 'VOTE';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_FAIL = 'VOTE_FAIL';

export const SEND_MESSAGES = 'SEND_MESSAGES';
export const SEND_MESSAGES_SUCCESS = 'SEND_MESSAGES_SUCCESS';
export const SEND_MESSAGES_FAIL = 'SEND_MESSAGES_FAIL';

export const SEND_LIKE = 'SEND_LIKE';
export const SEND_LIKE_SUCCESS = 'SEND_LIKE_SUCCESS';
export const SEND_LIKE_FAIL = 'SEND_LIKE_FAIL';

export const SEND_DISLIKE = 'SEND_DISLIKE';
export const SEND_DISLIKE_SUCCESS = 'SEND_DISLIKE_SUCCESS';
export const SEND_DISLIKE_FAIL = 'SEND_DISLIKE_FAIL';

export const SEND_REACTION = 'SEND_REACTION';
export const SEND_REACTION_SUCCESS = 'SEND_REACTION_SUCCESS';
export const SEND_REACTION_FAIL = 'SEND_REACTION_FAIL';
