export const CREATE_AUDITOR = 'CREATE_AUDITOR';
export const CREATE_AUDITOR_SUCCESS = 'CREATE_AUDITOR_SUCCESS';
export const CREATE_AUDITOR_FAIL = 'CREATE_AUDITOR_FAIL';

export const VOTE = 'VOTE';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_FAIL = 'VOTE_FAIL';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
